---
title: Himalay Sunuwar
timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

description: I am a programmer from Himalayas. I speak JavaScript, Java, Python and C#.
baseurl: ''
url: https://himalay.com.np

contacts:
- service: Email
  title: contact@himalay.com.np
  url: mailto:contact@himalay.com.np
- service: Twitter
  title: "@HimalaySunuwar"
  url: https://twitter.com/HimalaySunuwar
- service: Github
  title: "@himalay"
  url: https://github.com/himalay

include: ["_pages"]

markdown: kramdown
highlighter: rouge
permalink: pretty
production: true
