# Site settings
title: Himalay Sunuwar
email: your-email@domain.com
description: I am a programmer from Himalayas. I speak Java, Python and JavaScript.
baseurl: ''
url: https://himalay.com.np
contacts:
  - service: Email
    title: contact@himalay.com.np
    url: mailto:contact@himalay.com.np
  - service: Twitter
    title: '@HimalaySunuwar'
    url: https://twitter.com/HimalaySunuwar
  - service: Github
    title: '@himalay'
    url: https://twitter.com/himalay


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
